// import { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "About",
//   description: "Generated by create next app",
// };
'use client'
import Styles from './about.module.css'
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination } from 'swiper/modules';

export default function page() {
  return (
    <div className="container-fluid">
      <div className="row row-cols-1 row-cols-lg-2">
        <div className="col">
          <div className="fs-6">
            Provide Best
          </div>
          <div className="fs-3 fw-bold">
            Product For You
          </div>
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum labore maxime rem nobis veniam beatae! Molestias obcaecati ab, nemo dolor provident delectus iste doloribus adipisci enim beatae? Molestiae totam dolore doloribus fugit, sit alias maiores, fugiat aspernatur odio, illum sequi quod dolorum corporis animi at incidunt nobis perferendis. Consequuntur ipsam itaque, nemo non ea vitae dolorum quae atque voluptate consectetur, dolor vero assumenda suscipit eaque facilis, doloribus sit. Minima, corrupti.
          </p>
        </div>
        <div className="col">
          <img src="https://wixplosives.github.io/codux-assets-storage/add-panel/image-placeholder.jpg" alt="some Random Image" className={Styles.img_app} />
        </div>
      </div>
      <div className={`mt-2 h-100 ${Styles.back_img_continer}`}>
        <Swiper
          breakpoints={
            {
              0: {
                slidesPerView: 1,
                spaceBetween: 5
              },
            }
          }

          slidesPerView={1}
          pagination={{
            clickable: true,
          }}
          modules={[Pagination]}
          className="mySwiper"
        >
          {/* <SwiperSlide>Slide 1</SwiperSlide>
              <SwiperSlide>Slide 2</SwiperSlide>
              <SwiperSlide>Slide 3</SwiperSlide> */}
          <SwiperSlide >
            <div className='px-2 text-center h-100'>
              <img src="https://wixplosives.github.io/codux-assets-storage/add-panel/image-placeholder.jpg" alt="some Random Image" className={Styles.profile_img} />
              <div className='col-12'>
                <div className='ps-1'>
                  <p className='fs-5 text-wrap'> Lorem, ipsum.</p>
                </div>
                <div className='ps-1'>
                  <p className='w-100 text-wrap'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illo omnis voluptatum neque aliquam. Magnam, provident!... </p><span className={Styles.extraText} >Read more</span>
                </div>
              </div>
            </div>
          </SwiperSlide>
          <SwiperSlide >
            <div className='px-2 text-center h-100'>
              <img src="https://wixplosives.github.io/codux-assets-storage/add-panel/image-placeholder.jpg" alt="some Random Image" className={Styles.profile_img} />
              <div className='col-12'>
                <div className='ps-1'>
                  <p className='fs-5 text-wrap'> Lorem, ipsum.</p>
                </div>
                <div className='ps-1'>
                  <p className='w-100 text-wrap'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illo omnis voluptatum neque aliquam. Magnam, provident!... </p><span className={Styles.extraText} >Read more</span>
                </div>
              </div>
            </div>
          </SwiperSlide>
          <SwiperSlide >
            <div className='px-2 text-center h-100'>
              <img src="https://wixplosives.github.io/codux-assets-storage/add-panel/image-placeholder.jpg" alt="some Random Image" className={Styles.profile_img} />
              <div className='col-12'>
                <div className='ps-1'>
                  <p className='fs-5 text-wrap'> Lorem, ipsum.</p>
                </div>
                <div className='ps-1'>
                  <p className='w-100 text-wrap'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illo omnis voluptatum neque aliquam. Magnam, provident!... </p><span className={Styles.extraText} >Read more</span>
                </div>
              </div>
            </div>
          </SwiperSlide>
        </Swiper>
      </div>
     
    </div>
  )
}
