// import { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "About",
//   description: "Generated by create next app",
// };
'use client'
import Styles from './about.module.css'
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Autoplay } from 'swiper/modules';

export default function page() {
  return (
    <div className="container-fluid">
      <div className="row row-cols-1 row-cols-lg-2">
        <div className="col">
          <div className="fs-6">
            Provide Best
          </div>
          <div className="fs-3 fw-bold">
            Product For You
          </div>
          <p>
           There are so many products in all segment for according to customer taste. Some of the famous products are the Garam Masala, Bhaji Pav Masala etc.
          </p>
        </div>
        <div className="col">
        <img src="/IMG-20240818-WA0011.jpg" alt="some Random Image" className={Styles.img_app} />
        </div>
      </div>
      <div className={`mt-2 h-100 ${Styles.back_img_continer}`}>
        <Swiper
          breakpoints={
            {
              0: {
                slidesPerView: 1,
                spaceBetween: 5
              },
            }
          }
          autoplay={{
            delay: 2500,
            disableOnInteraction: false,
          }}
          slidesPerView={1}
          pagination={{
            clickable: true,
          }}
          modules={[Pagination, Autoplay]}
          className="mySwiper"
        >
          {/* <SwiperSlide>Slide 1</SwiperSlide>
              <SwiperSlide>Slide 2</SwiperSlide>
              <SwiperSlide>Slide 3</SwiperSlide> */}
          <SwiperSlide >
            <div className='px-2 text-center h-100'>
              <img src="/IMG-20240818-WA0001.jpg" alt="some Random Image" className={Styles.profile_img} />
              <div className='col-12'>
                <div className='ps-1'>
                  <p className='fs-5 text-wrap'> Dabeli Masala.</p>
                </div>
                <div className='ps-1'>
                  <p className='w-100 text-wrap'>Famous masala for to make/cook dabeli at home which also taste good & great for health. </p><span className={Styles.extraText} >Read more</span>
                </div>
              </div>
            </div>
          </SwiperSlide>
          <SwiperSlide >
            <div className='px-2 text-center h-100'>
              <img src="/IMG-20240818-WA0002.jpg" alt="some Random Image" className={Styles.profile_img} />
              <div className='col-12'>
                <div className='ps-1'>
                  <p className='fs-5 text-wrap'> Kashmiri Mirch</p>
                </div>
                <div className='ps-1'>
                <p className='w-100 text-wrap'>Famous masala for to make/cook dabeli at home which also taste good & great for health. </p><span className={Styles.extraText} >Read more</span>  </div>
              </div>
            </div>
          </SwiperSlide>
          <SwiperSlide >
            <div className='px-2 text-center h-100'>
              <img src="/IMG-20240818-WA0003.jpg" alt="some Random Image" className={Styles.profile_img} />
              <div className='col-12'>
                <div className='ps-1'>
                  <p className='fs-5 text-wrap'> Sambhar Masala</p>
                </div>
                <div className='ps-1'>
                <p className='w-100 text-wrap'>Famous masala for to make/cook dabeli at home which also taste good & great for health. </p><span className={Styles.extraText} >Read more</span>
                </div>
              </div>
            </div>
          </SwiperSlide>
        </Swiper>
      </div>
     
    </div>
  )
}
