import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import SiteFooter from "@/component/SiteFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kalpvruksh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} container-fluid`}>
        <Navbar />
        {children}
        <Footer />
        <SiteFooter />
        </body>
    </html>
  );
}
