// import { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "About",
//   description: "Generated by create next app",
// };
'use client'
import Styles from './product.module.css'
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination } from 'swiper/modules';
import { FaRupeeSign } from 'react-icons/fa';

export default function page() {
  return (
    <div className="container-fluid">
      <div className="row row-cols-1 row-cols-lg-2">
        <div className="col">
          <div className="fs-6">
            Provide Best
          </div>
          <div className="fs-3 fw-bold">
            Dabeli Masala
          </div>

        </div>
      </div>

      <div className="row row-cols-1 row-cols-md-2">
        <div className="col">
          <div className={`mt-2 h-100 ${Styles.back_img_continer}`}>
            <Swiper
              breakpoints={
                {
                  0: {
                    slidesPerView: 1,
                    spaceBetween: 5
                  },
                }
              }

              slidesPerView={1}
              pagination={{
                clickable: true,
              }}
              modules={[Pagination]}
              className="mySwiper"
            >
              {/* <SwiperSlide>Slide 1</SwiperSlide>
              <SwiperSlide>Slide 2</SwiperSlide>
              <SwiperSlide>Slide 3</SwiperSlide> */}
              <SwiperSlide >
                <div className='px-2 text-center h-100'>
                  <img src="/IMG-20240818-WA0001.jpg" alt="some Random Image" className={Styles.profile_img} />
                </div>
              </SwiperSlide>
              <SwiperSlide >
                <div className='px-2 text-center h-100'>
                  <img src="/IMG-20240818-WA0002.jpg" alt="some Random Image" className={Styles.profile_img} />
                 
                </div>
              </SwiperSlide>
              <SwiperSlide >
                <div className='px-2 text-center h-100'>
                  <img src="/IMG-20240818-WA0003.jpg" alt="some Random Image" className={Styles.profile_img} />
                
                </div>
              </SwiperSlide>
            </Swiper>
          </div>
        </div>
        <div className="col mt-4 mt-md-0">
          <h2>Dabeli Masala</h2>
          <p className='mt-3 fw-fw-bold fs-4'>Description </p>
          <p>
            Famous masala for to make/cook dabeli at home which also taste good & great for health.Famous masala for to make/cook dabeli at home which also taste good & great for health.Famous masala for to make/cook dabeli at home which also taste good & great for health.Famous masala for to make/cook dabeli at home which also taste good & great for health.Famous masala for to make/cook dabeli at home which also taste good & great for health.Famous masala for to make/cook dabeli at home which also taste good & great for health.
          </p>
          <p className='mt-3 fw-fw-bold fs-4'>Packing Sizes </p>
          <div className='row row-cols-3 row-cols-md-4'>
            <div className="col">
              <p className='fw-bold fs-6'>200gm</p>
            </div>
            <div className="col-8 col-md-9">
              <div className="d-flex justify-content-start text-start">
                <p className=' fs-6 d-flex align-items-center  text-decoration-line-through'>200<FaRupeeSign className=''/></p>
                <p className='fs-6 d-flex align-items-center ms-3'>200<FaRupeeSign/></p>
              </div>
            </div>
          </div>
          <div className='row row-cols-3 row-cols-md-4'>
            <div className="col">
              <p className='fw-bold fs-6'>500gm</p>
            </div>
            <div className="col-8 col-md-9">
              <div className="d-flex justify-content-start text-start">
                <p className=' fs-6 d-flex align-items-center  text-decoration-line-through'>500<FaRupeeSign className=''/></p>
                <p className='fs-6 d-flex align-items-center ms-3'>500<FaRupeeSign/></p>
              </div>
            </div>
          </div>
          <div className='row row-cols-3 row-cols-md-4'>
            <div className="col">
              <p className='fw-bold fs-6'>1000gm/1kg</p>
            </div>
            <div className="col-8 col-md-9">
              <div className="d-flex justify-content-start text-start">
                <p className=' fs-6 d-flex align-items-center  text-decoration-line-through'>1200<FaRupeeSign className=''/></p>
                <p className='fs-6 d-flex align-items-center ms-3'>1200<FaRupeeSign/></p>
              </div>
            </div>
          </div>
          <div className='row row-cols-3 row-cols-md-4'>
            <div className="col">
              <p className='fw-bold fs-6'>5000gm/5kg</p>
            </div>
            <div className="col-8 col-md-9">
              <div className="d-flex justify-content-start text-start">
                <p className=' fs-6 d-flex align-items-center  text-decoration-line-through'>1500<FaRupeeSign className=''/></p>
                <p className='fs-6 d-flex align-items-center ms-3'>1400<FaRupeeSign/></p>
              </div>
            </div>
          </div>
       
        </div>
      </div>
    </div>
  )
}
